### ISSUE TITLE
Writing ROS nodes, lesson 2: quiz contradicts to lesson

### ISSUE THREAD

**Issue by bartmate** [udacity/sdc-issue-reports#1008]
Lesson says that in synchronous case, the publisher is blocked until the other publisher is done.
In the popup coming out for the (wrong) answer "None", it is said that this choice indicates the synchronous case and so the message will be dropped.
This seems contradiction regarding what will happen with the message.

**Comment by baumanab** [comment]
Thanks for writing in about this.  This doesn't seem like a contradiction.  In the scenario we are sending messages at about the same rate we receive them +/- 1/20th of a second.  This means that we could get two messages that overlap.  In the None case, the overlapped message will be dropped since the publisher is busy.  We need to use a queue size that is robust to this overlap.  Does that make sense?

**Comment by bartmate** [comment]
Yes, the solution is OK, I agree.

What contradict are the lesson and the content of the popup for the wrong answer 'None'. One says blocking (i.e. waiting and not loosing message), the other says dropping message which I think is a contradiction. 

Of course, I could misunderstand something.

**Comment by baumanab** [comment]
Ah, I see your point now.  I have changed the wording from drops to blocks.
