### ISSUE TITLE
Term 1, lesson 4.1 NOT Perceptron quiz

### ISSUE THREAD

**Issue by jwetherb** [udacity/sdc-issue-reports#1114]
I'm in the September 2017 cohort, taking term 1, and I'm seeing a bug in the lesson 4.11 quiz on NOT Perceptron behavior.

The problem seems to be in the line below:

  output = int(linear_combination >= 0)

which returns 0 for a linear_combination < 0, and 1 for anything else. This doesn't match the "if 0 then 1 elif 1 then 0" expected behavior described in the text.

**Comment by jwetherb** [comment]
Btw, the line above is calculating the step function.

**Comment by baumanab** [comment]
Thanks for the feedback on this quiz.  The quiz is actually correct.  Recall that we are building a NOT gate by linear combination of our equation terms.  We want to ignore input 1 and apply NOT to input 2.  So, for (0,0) we should return TRUE since input 2 is a 0.  For (0,1) FALSE, (1,0)  TRUE, etc.   So, we have to adjust weights and bias such that the output of the linear combination will be 0 or positive when input 2 is 0, and negative when input 2 is 1.  We could do this output = int(linear_combination <= 0), in which case we would reverse the sign of one of our weights .  The direction of the Boolean operator doesn't change the nature of the problem.  Does that clarify?

**Comment by jwetherb** [comment]
Thank you for your reply, Andrew. My confusion was I thought the objective of setting the weights and bias was to get the linear_combination to result in 0 when input 2 was set to 1, and 1 when input 2 was set to 0. Instead I can see now (from rereading the initial Perceptron lesson) that the linear_combination is then fed to an activation function (the Heaviside step function, which is the output = int(linear_combination <= 0) step that calculates the actual 1/0 output.

**Comment by baumanab** [comment]
Yes, the activation function is a key component in NN based networks.  For a perceptron, we have binary step function.  Typically though we would actually use a sigmoid activation in the final layer.
