### ISSUE TITLE
Term 2: uWebSockets installation suggestion

### ISSUE THREAD

**Issue by subodh-malgonde** [udacity/sdc-issue-reports#1136]
Hi, I am a forum mentor. [There is student, who setup uWebSockets on Windows](https://discussions.udacity.com/t/unable-to-connect-simulator-1-3-to-project-v2-on-windows-10/249197/16?u=subodh.malgonde). Apparently with a few tweaks, the process can be automated in a single script for Windows user. He is willing to post a detailed step by step guide which you can incorporate in the classroom material. I have asked him to add more details here.

**Comment by baumanab** [comment]
That sounds really helpful. We would be happy to post that in the classroom.

**Comment by paul-michalik** [comment]
Yes, this can be automated using, for example, [vcpkg](https://github.com/Microsoft/vcpkg), a homebrew-style package manager targeting Windows as a development host system. Something similar to the script [install-windows.bat](https://github.com/paul-michalik/CarND-Extended-Kalman-Filter-Project) could be used to install uWebSockets along all its dependencies for a specified "triplet" (= target platform). There are several options how to integrate vcpkg packages with the development environment, I used projectwise integration via NuGet. In order to automate this without too much tweaking, afaik, at least following changes in the  Udacity project setup are required:

- Use current master of uWebSocket and update the main.cpp to use the pointer signatures for callbacks
- The CMakeLists.txt should be rewritten to comply with modern cross platform CMake style. The way it's implemented right now, it basically only works in a linuxoidal gcc environment, even the MacOS version needs to be hacked. This would inculde the usage of `find_package` to locate the dependencies or setting up the environment in platform specific bootstrapping scripts.
- Alternatively, a MSBuild based configuration could be provided for Windows, this is what I did in my repo.

**Comment by baumanab** [comment]
Thank you for this information.  I was wondering if anyone could provide me with some insight regarding use of Ubuntu BASH.  I use both Windows and Linux, but spent most of my computing experience on Linux, Unix, or on MS command line environments (didn't move to Windows for a long time).  So, I'm very comfortable with Ubuntu BASH and it seems like this is a  very convenient option for Windows 10 users.  It also seems like a setup directly on Windows is very challenging.  Given this, what do you see as the advantages of not using Ubuntu BASH and using the native Windows OS instead? Understanding this will help with environment setup instructions.

**Comment by paul-michalik** [comment]
@baumanab Actually, it's a very inconvenient choice for Windows users. It is fine for quickly checking stuff or as a scripting environment for linuxoidal tools. However, it is highly inconvenient as a software development environment if you are used to the comfort and productivity of Visual Studio. A native setup on Windows isn't challenging at all it just requires knowledge of the native tools for dependency management - either NuGet or vcpkg, or both. Also a CMake based configuration is possible but this requires a truly platform independent configuration. In both cases you can stick with CLI + text editor if you wish but as a Windows developer you definitely want to use Visual Studio...

**Comment by baumanab** [comment]
That makes sense. Thanks for the insight. I'm going to delve into this. I'll post any needs for clarification here. Any response to those posts will be appreciated. A unified windows solution is of great value. Thank you for your advocacy.

**Comment by baumanab** [comment]
Thanks for developing this profile. I'll add it in by the end of the week.

**Comment by baumanab** [comment]
The IDE profile is now linked in the term 2 environment setup for Windows concept.
