### ISSUE TITLE
Term 2, Lesson 7 section 22,23 wrong equations

### ISSUE THREAD

**Issue by anasmatic** [udacity/sdc-issue-reports#1159]
1 - in lesson 22 mean and covariance equations are not explained properly, which leads to hard times in the next quiz 
2 - value of i -under summation mark- in one of the equations is wrong (check vid @0:40) 
3 - lamda equation for index 0 , and 2+, but no equaions for index 1 (check vid @0:50)
4 - what is over the summation symbol ? n_sigma ? or n_a , and what is the value of n_a or n_sigma ? is it the width of sigma_points_matrix ? or the height ? or the new matrix width or what ? this is not explained in the class or the quiz.
5 - in quiz 23, equations are using one-based-index-format for i , which leads to confusion added to the confusion resulted from last lesson mistakes.

thank you.

**Comment by baumanab** [comment]
Additional Student comments regarding [Predicted Mean and Covariance(https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/0949fca6-b379-42af-a919-ee50aa304e6a/lessons/daf3dee8-7117-48e8-a27a-fc4769d2b954/concepts/bf42ab6c-89db-4459-898f-4f270162edc0)

Equations here do not match the video equations (it appears the video equations are not correct):

![image](https://user-images.githubusercontent.com/4316306/33732979-15d666d8-db3d-11e7-8966-58d6bd26ce35.png)


![image](https://user-images.githubusercontent.com/4316306/33732990-1e72519e-db3d-11e7-8d8b-d9b29454970d.png)

- the sum in the video goes to 2 * n_sigma and the indices of the weights are incorrect
  
- n_aug and n_sig may have been switched

- weight indices are wrong in the video. the second weight equation should start from i=1, not 2. Otherwise i=1 is undefined
 - the indices should be equal, otherwise, it’s quite confusing. sometimes it starts at 0, sometimes at 1.

**Comment by mvirgo** [comment]
Hi there! With Waffle closing its doors next month, and the ability to leave more detailed feedback on each classroom page (see “Send Feedback” in the upper right if you are enrolled in the program), we are migrating away from our Waffle board. All issues and conversations here will be migrated onto our internal platforms. 

Over the next week, I am leaving these notes in case anyone has further follow-ups they want to get in before the board closes, as well as migrating over the tickets. As of 4/19, I will close all the remaining open tickets, and archive the related Github repository.
