### ISSUE TITLE
Term1 Lesson 3.20 SoftMax Quiz wont accept vectorized solution

### ISSUE THREAD

**Issue by toshas** [udacity/sdc-issue-reports#1261]
def softmax(L):
    Lexp = np.exp(L)
    LexpSum = np.sum(Lexp)
    Lexp *= (1/LexpSum)
    return Lexp.tolist()

Trying for L=[5,6,7]. The correct answer is [0.090030573170380462, 0.24472847105479764, 0.6652409557748219] And your code returned [0.09003057317038046, 0.24472847105479767, 0.6652409557748219]Hmm... there must be a mistake.

**Comment by baumanab** [comment]
Thanks for pointing this out.  The issue was one of precision.  There is a slightly different result for the second item in the list. 
Trying for L=[5,6,7].
The correct answer is
[0.090030573170380462, 0.24472847105479764, 0.6652409557748219]
And your code returned
[0.09003057317038046, 0.24472847105479767, 0.6652409557748219]

The grader was looking for array equality.  It has now been changed to np.isclose(), which evaluates this as correct.
