### ISSUE TITLE
Term1 Lesson 3.28 Logistic Regression algorithm acceptance issue

### ISSUE THREAD

**Issue by toshas** [udacity/sdc-issue-reports#1262]
Here is the code I wrote. It passes the "Test" button, but when I attempt to submit, there is a convoluted message:

Try Again
Oops, looks like you got an error!
`invalid index to scalar variable.`

```
def dErrors(X, y, y_hat):
    y_minus_y_hat = y - y_hat
    x1 = np.transpose(X)[0]
    x2 = np.transpose(X)[1]
    DErrorsDx1 = -np.multiply(np.array(y_minus_y_hat), x1)
    DErrorsDx2 = -np.multiply(np.array(y_minus_y_hat), x2)
    DErrorsDb = -np.array(y_minus_y_hat)
    return DErrorsDx1, DErrorsDx2, DErrorsDb

def gradientDescentStep(X, y, W, b, learn_rate = 0.01):
    y_hat = prediction(X, W, b)
    y_hat_arr = np.transpose(y_hat)[0]
    DErrorsDx1, DErrorsDx2, DErrorsDb = dErrors(X, y, y_hat_arr)
    W[0] -= learn_rate * np.sum(DErrorsDx1)
    W[1] -= learn_rate * np.sum(DErrorsDx2)
    b -= learn_rate * np.sum(DErrorsDb)
    e = error(y, y_hat)
    return W, b, e    
```

**Comment by baumanab** [comment]
Thanks for reporting this.  We did some investigation and this doesn't seem to be a bug.  The message is due to the grading code evaluation a 2D array.  The answer returned by the code above is a 1D array.  Also, not all of the values are correct.  Here is result of gradient descent for the code above:

array([array([[ 0.51559966],
       [ 0.49559966]]), 0.49559966192604504,
       array([ 0.53091106])], dtype=object)

Here is the result for the Udacity solution:

array([array([[ 0.51559966],
       [ 0.49559966]]), array([ 0.49559966]),
       array([ 2.12364423])], dtype=object)

It's not clear to me what is causing the issue from the code in this post.  It may help to run the code locally, that way debugging is much easier.  If you do encounter a bug in the classroom or there is something that could be made more clear regarding the instructions, please open a ticket and we will address it.
