### ISSUE TITLE
Term1 L7 P33 Quiz fails a different solution

### ISSUE THREAD

**Issue by EmilePapillon** [udacity/sdc-issue-reports#1318]
the following code will fail the quiz but outputs the correct answer (same answer as "quiz_solution.py" when the code is copy-pasted into "solution.py")

import math
def batches(batch_size, features, labels):
    """
    Create batches of features and labels
    :param batch_size: The batch size
    :param features: List of features
    :param labels: List of labels
    :return: Batches of (Features, Labels)
    """
    assert len(features) == len(labels)
    # TODO: Implement batching
    num_samples = len(features)
    output = []
    num_left_alone_samples  = num_samples % batch_size
    num_complete_samples = num_samples - num_left_alone_samples
    
    #make complete samples
    batch = [features[0:num_complete_samples:1],labels[0:num_complete_samples:1]]
    output.append(batch)
    #make rest of samples
    batch = [features[num_complete_samples::1],labels[num_complete_samples::1]]
    output.append(batch)
    
    return output

**Comment by EmilePapillon** [comment]
A part of the code appeared truncated in the description so I a writing it again here:

    batch = [features[0:num_complete_samples:1],labels[0:num_complete_samples:1]]
    output.append(batch)

    batch = [features[num_complete_samples::1],labels[num_complete_samples::1]]
    output.append(batch)
    
    return output

**Comment by baumanab** [comment]
Thank you for reporting this.  It does look like the outputs are identical.  We are looking into this.

**Comment by baumanab** [comment]
I took a closer look at this.  It does appear that the grader is working.  The test uses a batch size of 128 and the number of samples is 5500.  So, the number of batches should 43.  This is check by looking at the length of the output.  The correct answer will give a length of 42 (0 indexed, so this is 43 batches).  The output from the code provided above has a length of 2.  

- shape of Udacity solution output: is (43L, 2L). 
- shape of solution from above output (2L, 2L).  It looks like the first element of the array is one large array of 5376 elements. 

It may be worth trying some other approaches and reaching out to a mentor.  I think the issue is that the solution works well for the test case in the classroom but more complex/larger test cases require iterating over the array.  I hope that makes sense.
