### ISSUE TITLE
T2 Markov Localization : Control standard deviation vs Position standard deviation

### ISSUE THREAD

**Issue by Nk911** [udacity/sdc-issue-reports#1355]
Hello All,

I am not able to get the difference between control standard deviation and position standard deviation in ch.9 Solution: Initialize Priors Function1.(https://classroom.udacity.com/nanodegrees/nd013-connect/parts/7dc7c9b7-2884-4e43-bf15-2d1e1a121081/modules/9688ee0e-ef68-4a26-ae60-c4b24eae8e6f/lessons/f5785f6a-ecb4-42a8-bf2d-b8f531ce0dde/concepts/4e653fee-d7b1-4519-9f02-2d9dbaa5ddb8)

First of all I am not getting what they mean by control_stdev and what is significance ? (Q1)

They have used control_stdev inside initialize_priors function to calculate normalization_term and hardcoded the position_stdev value as 1.

In the footnote it is mentioned that

A more robust approach would be to create a function that accepts a position standard deviation as an argument and adjusts initialization and normalization based on its value.

If is it so why have they used control_stdev to calculate normalization_term? (Q2)

45 : float normalization_term = landmark_positions.size() (control_stdev 2 + 1);

Moreover In the footnote they have also mentioned

A solution for a position standard deviation of 2.0 and a control standard deviation of 1.0 is:

for (unsigned int i = 0; i < landmark_positions.size(); i++){ int landmark_center = landmark_positions[i]; priors[landmark_center] = 1.0f/normalization_term; priors[landmark_center - 2] = 1.0f/normalization_term; priors[landmark_center + 2] = 1.0f/normalization_term; priors[landmark_center - 1] = 1.0f/normalization_term; priors[landmark_center + 1] = 1.0f/normalization_term; }

normalization_term (9) will be the same as control_stdev = 1

if we go by this solution then prior vector will be having 15 position (5 for each landmark) filled with 1/9 and total probability will be 15/9 which is greater than 1 hence prior is non-normalized. How is it possible? (Q3)

Please correct me if i am wrong and if not could someone answer my questions?

Thanks

**Comment by baumanab** [comment]
Sorry for the confusion.  Hopefully, my inline responses will be helpful.  Either way, let us know.

Hello All,

I am not able to get the difference between control standard deviation and position standard deviation in ch.9 Solution: Initialize Priors Function1.(https://classroom.udacity.com/nanodegrees/nd013-connect/parts/7dc7c9b7-2884-4e43-bf15-2d1e1a121081/modules/9688ee0e-ef68-4a26-ae60-c4b24eae8e6f/lessons/f5785f6a-ecb4-42a8-bf2d-b8f531ce0dde/concepts/4e653fee-d7b1-4519-9f02-2d9dbaa5ddb8)

First of all I am not getting what they mean by control_stdev and what is significance ? (Q1)

They have used control_stdev inside initialize_priors function to calculate normalization_term and hardcoded the position_stdev value as 1.

**I can see how this would be confusing, I'm thinking we need to add a note in the classroom.  So the control stdev is essentially the spread from movement (movement is the result of our control input in this case).  So, we input a control of moving 1 step but our actual movement could be in the range of 1 +/- control-stdev.  The position stdev is the spread in our actual position.  So, we think we are at a particular location, but we could be anywhere in location +/- position-stdev.**


In the footnote it is mentioned that

A more robust approach would be to create a function that accepts a position standard deviation as an argument and adjusts initialization and normalization based on its value.

If is it so why have they used control_stdev to calculate normalization_term? (Q2)

45 : float normalization_term = landmark_positions.size() (control_stdev 2 + 1);

**Good catch! This is an error, it should be position_stdev, we will update.**

Moreover In the footnote they have also mentioned

A solution for a position standard deviation of 2.0 and a control standard deviation of 1.0 is:

for (unsigned int i = 0; i < landmark_positions.size(); i++){ int landmark_center = landmark_positions[i]; priors[landmark_center] = 1.0f/normalization_term; priors[landmark_center - 2] = 1.0f/normalization_term; priors[landmark_center + 2] = 1.0f/normalization_term; priors[landmark_center - 1] = 1.0f/normalization_term; priors[landmark_center + 1] = 1.0f/normalization_term; }

normalization_term (9) will be the same as control_stdev = 1

if we go by this solution then prior vector will be having 15 position (5 for each landmark) filled with 1/9 and total probability will be 15/9 which is greater than 1 hence prior is non-normalized. How is it possible? (Q3)

**The map and other elements would have to adjust dynamically as well.  This footnote was added in response to [this issue](https://github.com/udacity/sdc-issue-reports/issues/1342).  This problem is meant to be a lower complexity example rather than adaptive, production ready code.  That being said we can try to clarify certain elements.**

Please correct me if i am wrong and if not could someone answer my questions?

Thanks

**Comment by Nk911** [comment]
![term2_sdc_issue_error](https://user-images.githubusercontent.com/6182762/38914518-4a4563ec-42fd-11e8-823d-a7a34a4a7cef.JPG)

1. There is still an issue in the solution, please refer attached screenshot
2. Please include the definition of control_stddev in the footnote in the same chapter or wherever it is introduced
