### ISSUE TITLE
Inaccurate equation for CTRV when ​​​ψ' = 0

### ISSUE THREAD

**Issue by aoool** [udacity/sdc-issue-reports#1356]
In Unscented Kalman Filters lesson (Term 2) in step "20. Sigma Point Prediction Assignment 1" udacity provides an equation for state transition (CTRV model) for the case when  ​ψ' = 0. However, the product ​ψ'Δt is still specified in the equation. Since it equals to zero, you should replace ​​ψ'Δt with 0.

**Comment by aoool** [comment]
I also think that it should be mentioned in "7. CTRV Zero Yaw Rate".

**Comment by baumanab** [comment]
It’s true that when yaw rate is zero the term is zero. However, we need to keep it in the matrix operation to maintain dimensions. If we remove it we lose a dimension.

**Comment by aoool** [comment]
Why would we loose a dimension if we set ​ψ'Δt as 0? We will still have 5 dimensions. What I am trying to say is that it is confusing when we write an equation for the case ​ψ' = 0 and keeping this term (this symbol) in the equation.

**Comment by baumanab** [comment]
Sorry, I misunderstood, I thought you were suggesting removing the term.  I can see where leaving the term in the equation would become confusing.  However, it's best to leave the terms in vs. assigning to 0, so that portion of the equation/matrix becomes consistent, with the right side changing on the value of yaw_rate.
