### ISSUE TITLE
Miniflow (#8 Linear Transform) Eq. 2 seems wrong

### ISSUE THREAD

**Issue by gtg162y** [udacity/sdc-issue-reports#136]
Equation 2 seems wrong. How can Z be a matrix if b is a vector? (When adding matrices and vectors, the dimensions should match). Instead, it should be: Z = XW + B where X is m by n, B is m by k, B is B by k, W is n by k (m is batch size, n is number of features per example, k is number of output per example). B is basically m copies of the 1 by k vector b.

**Comment by domluna** [comment]
@gtg162y that's a fair point. Z = XW + b lines up more directly with numpy code `np.dot(X, W) + b` which is doing the broadcasting under the hood.

https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html. Broadcasting is very common since it's very wasteful to create to a matrix of repeat column or rows, especially if there are memory constraints.

I'll make a further note about the notation.

**Comment by gtg162y** [comment]
Got it. Thanks.
