### ISSUE TITLE
Semantic Segmentation does not have the "Elective" tag in its title

### ISSUE THREAD

**Issue by EmilePapillon** [udacity/sdc-issue-reports#1433]
In term 3, the first elective project on functional safety bares the mention "Elective Project" in its title, but not the Semantic Segmentation. Also, in an ideal world people who chose the functional safety project should not be receiving a deadline warning email about the semantic segmentation project. Ideally, all the lessons about elective material should have "Elective: " in front of their titles.

**Comment by mvirgo** [comment]
On your first item, good idea. I've updated it as such.

On the second item for the email, unfortunately we don't have it set up to do so on the back-end, and SDC is the only one with this type of set-up. With no electives included in the newer two-term version of the program, we don't plan to do any further work to implement that.

For the last one, we try to keep the length of the lesson titles below a certain maximum, which would get crossed if we added "Elective: " to each, and this is otherwise fairly well indicated in the first lesson of both electives.

Thanks for the note!
