### ISSUE TITLE
Workspace lesson broken link

### ISSUE THREAD

**Issue by ahmedmbakr** [udacity/sdc-issue-reports#1438]
In project: Kidnapped vehicle, lesson 4 which is (Project instruction) you wrote:
"For tips on workspace use, please review the [Workspaces](https://classroom.udacity.com/nanodegrees/nd013/parts/edf28735-efc1-4b99-8fbb-ba9c432239c8/modules/c773ee09-4a0d-445d-b6af-0739e6653f18/lessons/ec7a3d6d-24a6-4dad-9f5c-aacd29763e0b/concepts/undefined) lesson."
But the link for the workspaces lesson does not work and the following error message appears:
"You are not allowed to access this Nanodegree Program. Is your subscription paused, or past due?".

**Comment by mvirgo** [comment]
Thanks for the note. We've actually been taking these out as they come up, because we can't link between separate versions of the Nanodegree program (i.e. the two-term vs. three-term version). I think static content access also affects this since the Workspaces lesson is in Term 1.

For right now, I have just removed the link and pointed to where it resides (Term 1), but hopefully we'll eventually have a better fix to links like this.
