### ISSUE TITLE
Viewing the camera image stream erro 

### ISSUE THREAD

**Issue by ahmedwahdan** [udacity/sdc-issue-reports#1444]
running the command
`rqt_image_view /rgb_camera/image_raw`
```
[ERROR] [1548318724.796441352]: Failed to load nodelet [rqt_image_view/ImageView_0] of type [rqt_image_view/ImageView]: Failed to load library /opt/ros/kinetic/lib//librqt_image_view.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libopencv_core3.so.3.3: cannot open shared object file: No such file or directory)
RosPluginlibPluginProvider::load_explicit_type(rqt_image_view/ImageView) failed creating instance
PluginManager._load_plugin() could not load plugin "rqt_image_view/ImageView": RosPluginlibPluginProvider.load() could not load plugin "rqt_image_view/ImageView"
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
Aborted (core dumped)

```

**Comment by mvirgo** [comment]
Closing since no further comments.

**Comment by shalaka7** [comment]
Hi @mvirgo ,

Initially I was getting the same error as author and then I tried the solution you posted above which started giving me more errors as below:

Any idea what could help with this? I am stuck on testing my camera due to this.

`
(venv) root@31c23da1c812:~/catkin_ws# rqt_image_view /rgb_camera/image_raw
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_dep/plugin.xml" in package "rqt_dep" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_py_console/plugin.xml" in package "rqt_py_console" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_shell/plugin.xml" in package "rqt_shell" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_web/plugin.xml" in package "rqt_web" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_dep/plugin.xml" in package "rqt_dep" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_py_console/plugin.xml" in package "rqt_py_console" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_shell/plugin.xml" in package "rqt_shell" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_web/plugin.xml" in package "rqt_web" not found
[ERROR] [1553395904.289301290]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_dep/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.289397751]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_web/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.289460240]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_shell/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.289521550]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_py_console/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.290094243]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_dep/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.290176042]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_web/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.290251882]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_shell/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.290309714]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_py_console/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.296788563]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_graph/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.296878567]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_publisher/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.296949719]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_gui_py/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.297015398]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_moveit/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.297325323]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_tf_tree/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.297389818]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_topic/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.297454167]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_robot_steering/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.297507312]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_rviz/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.297566896]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_plot/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.297631856]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_msg/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.297768107]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_runtime_monitor/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.297848504]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_srv/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.297917448]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_service_caller/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.297992081]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_bag/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.298064679]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_nav_view/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.298125590]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_console/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.298199606]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_logger_level/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.298247833]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_top/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.298287046]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_reconfigure/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.298338522]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_pose_view/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.298392293]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_launch/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
[ERROR] [1553395904.298453212]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/rqt_robot_monitor/plugin.xml' has no Root Element. This likely means the XML is malformed or missing..
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_action/plugin.xml" in package "rqt_action" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_bag/plugin.xml" in package "rqt_bag" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_console/plugin.xml" in package "rqt_console" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_graph/plugin.xml" in package "rqt_graph" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_gui_py/plugin.xml" in package "rqt_gui_py" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_launch/plugin.xml" in package "rqt_launch" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_logger_level/plugin.xml" in package "rqt_logger_level" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_moveit/plugin.xml" in package "rqt_moveit" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_msg/plugin.xml" in package "rqt_msg" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_nav_view/plugin.xml" in package "rqt_nav_view" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_plot/plugin.xml" in package "rqt_plot" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_pose_view/plugin.xml" in package "rqt_pose_view" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_publisher/plugin.xml" in package "rqt_publisher" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_reconfigure/plugin.xml" in package "rqt_reconfigure" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_robot_monitor/plugin.xml" in package "rqt_robot_monitor" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_robot_steering/plugin.xml" in package "rqt_robot_steering" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_runtime_monitor/plugin.xml" in package "rqt_runtime_monitor" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_rviz/plugin.xml" in package "rqt_rviz" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_service_caller/plugin.xml" in package "rqt_service_caller" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_srv/plugin.xml" in package "rqt_srv" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_tf_tree/plugin.xml" in package "rqt_tf_tree" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_top/plugin.xml" in package "rqt_top" not found
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/kinetic/share/rqt_topic/plugin.xml" in package "rqt_topic" not found
[ERROR] [1553395904.338670786]: Failed to load nodelet [rqt_image_view/ImageView_0] of type [rqt_image_view/ImageView]: Failed to load library /opt/ros/kinetic/lib//librqt_image_view.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libopencv_core3.so.3.3: cannot open shared object file: No such file or directory)
RosPluginlibPluginProvider::load_explicit_type(rqt_image_view/ImageView) failed creating instance
PluginManager._load_plugin() could not load plugin "rqt_image_view/ImageView": RosPluginlibPluginProvider.load() could not load plugin "rqt_image_view/ImageView"
`

**Comment by shalaka7** [comment]
I have re-done everything to fix above problem in my last comment.

To fix the problem by author, followed steps from here: https://github.com/ros/ros-overlay/issues/104

More specifically problem was ```LD_LIBRARY_PATH``` did not contain ```/opt/ros/kinetic/lib/x86_64-linux-gnu```

Running following command fixed it

```bash
source /opt/ros/kinetic/setup.bash

```
