### ISSUE TITLE
add cd command to TensorFlow lab instructions

### ISSUE THREAD

**Issue by gilcarmel** [udacity/sdc-issue-reports#147]
Minor correction to this page:
https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/91cc6685-08df-4277-b53d-3a792b02420d/concepts/b619c2f0-24e3-4529-aa48-9bcdba47cd08

After cloning the repo, you need to:
```
cd CarND-TensorFlow-Lab/
```

**Comment by johannesdeselaers** [comment]
+1

**Comment by Brok-Bucholtz** [comment]
Hey @gilcarmel,

Thanks for reporting the issue.  I'm assuming you're getting the error `environment.yml file not found`.  Instead of adding `cd CarND-TensorFlow-Lab/`, I changed the command
`$ conda env create -f environment.yml`
to
`$ conda env create -f CarND-TensorFlow-Lab/environment.yml`

This will fix this error, but if there is a different error, please let me know.
