### ISSUE TITLE
what is target acc% for p2?

### ISSUE THREAD

**Issue by giladgressel** [udacity/sdc-issue-reports#157]
A number of students are asking what the performance requirements are for a passing P2 assignment.  It is not clearly listed anywhere

**Comment by domluna** [comment]
TLDR: for now there isn't one but in the future there might be.

There isn't one that's been set. Mainly since the project shipped before the convnet, relu, and dropout portions of the TensorFlow lesson were fully complete. So fully connected networks would be fine and hence the accuracy would be a much lower than a convnet.
