### ISSUE TITLE
A way to keep track of changes made to the course content

### ISSUE THREAD

**Issue by gtg162y** [udacity/sdc-issue-reports#166]
I was under the impression that after I complete a particular lesson (i.e. 100% complete), if there is any changes or new material added to that lesson, then it will show that it is no longer 100%. That way I know that I need to revisit that lesson. But apparently that's not the case. 

Case in point, I finished Miniflow a couple weeks ago and at that time the backpropagation section was different than it is now (more details have been added now), but it was still showing 100% complete for the miniflow lesson.

Only after I manually went through the entire miniflow lesson again that I noticed the difference. Given there are likely going to be more changes in the future (guinea pig!) it'll be very helpful to have it automatically show what changes have been made. Thanks,

**Comment by gtg162y** [comment]
Since this has been open for a couple weeks, just wanted to remind you guys to please address it. It will be very helpful to know which lessons need to be re-visited (if important changes have been made to it).

**Comment by dsilver829** [comment]
This is a good point.

A "track history" feature for Udacity classroom content is beyond the scope of this Waffleboard, and in any case it sounds like that's not exactly what you're requesting.

For background, if a student complete a "concept" (a video, text node, etc.), it gets marked as complete. If we then edit that concept, it's still marked as complete for the student.

However, if we delete that concept and add a new concept, then the student's lesson completion decreases from 100% to 95% (or whatever the appropriate percentage is).

So we need to be mindful when making fairly large changes to a concept that we should create new concepts for that, instead of just editing existing concepts. We've discussed this as a team and will try to be mindful of that moving forward.

Thanks for the pointer.
