### ISSUE TITLE
TensorFlow Lab Windows Docker Notebook Page not Found

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#169]
I think there's a wrong command on that page perhaps.

For me, I cloned the repo in my D:// drive on Windows. 

So in D:\ I ran 

`docker run -it -p 8888:8888 -v 'pwd':/notebooks udacity/carnd-tensorflow-lab`

When I run the above, and try to access it via the browser I get a `404:Page not Found error`.

This is what didn't make sense to me. Why we are using `/notebooks` above instead of the cloned folder where we have the lab.ipynb

So I changed the above command to -

`docker run -it -p 8888:8888 -v 'pwd':/CarND-TensorFlow-Lab udacity/carnd-tensorflow-lab`

Replaced "notebooks" with the name of the cloned folder. 

I try to access it in the browser, and I can easily access it.

For a check, I ran the first cell, and got the correct output indicating everything was imported. 

I am not sure if this is infact an error or something I changed in the process. Clarification would be helpful. Thanks!

**Comment by domluna** [comment]
I believe on windows you have to do ${pwd} instead of `pwd`, but I don't use it so I'm not sure. Going off this https://github.com/udacity/CarND-Term1-Starter-Kit/blob/master/windows.md

Not sure why changing /notebooks to /CarND-TensorFlow-Lab would do anything. By the way there's a experimental docker image that was all the software needed for term1.

https://github.com/udacity/CarND-Term1-Starter-Kit
https://hub.docker.com/r/udacity/carnd-term1-starter-kit/

**Comment by sahiljuneja** [comment]
@domluna Thanks for the reply.

But if on windows I have to use ${pwd} shouldn't that be included in the command on the course page too?

And I went through the first problem and reached the checkpoint. I closed everything because it said it's been all saved into that pickle file. 

I restarted it all, and there was nothing saved. So I don't know why the commands in the course page not working, and I don't know why changing that command to something that works doesn't save anything. 

I will keep digging into this, but if anyone who has worked with that part of the course using docker on windows could help out and clarify things that would be great!

**Comment by sahiljuneja** [comment]
Thanks to another student I found the solution to part of the problem. To access it in the browser, we had to use the Docker IP as detailed here 

https://carnd-udacity.atlassian.net/wiki/questions/14288153/answers/14288966

```you can navigate to http://192.168.99.100:8888 to access the jupyter notebook which is running inside docker from your host browser.```

I think this should be added and explained in the course page?

Secondly, there should be an additional section there explaining how to actually save data locally on our systems. Based on the answers and comments in the above link, it seems there's an additional command to do that. Because after the code created the pickle file, I couldn't find it on my system. Because it's not being saved locally, it's being saved in the docker container. 

Lastly, a bit more detail on what happens on our system in terms of size being taken up by this. When I ran commands to download and uncompress the data, a couple of GBs were used up in my C drive. So perhaps some text explaining how or why that space is used up and how to recover it later? 

I think the above 3 details would really help us. Let me know what you think.

**Comment by mslavescu** [comment]
@sahiljuneja in order to see in host the changes done in docker or the other way you'll need to use the :shared option on your -v command like I do here (this works fine on Linux, it may not work on Windows):

docker run --env="DISPLAY" --volume="$HOME/.Xauthority:/root/.Xauthority:rw" -env="QT_X11_NO_MITSHM=1" -v /dev/video0:/dev/video0 -v /tmp/.X11-unix:/tmp/.X11-unix:ro -it -p 8888:8888 -p 6006:6006 -v ~/sharefolder:/sharefolder:shared gtarobotics/udacity-sdc bash

If it doesn't work, you can still get your files from docker, using SSH or even Github.
Just export port 22 like this (ensure SSH server is running in docker instance):
-p 2222:22
and use WinSCP to copy the files in and out:
https://winscp.net/eng/download.php

**Comment by MattHarrington** [comment]
PowerShell (preferred)
`docker run -it -p 8888:8888 -v ${pwd}:/CarND-TensorFlow-Lab udacity/carnd-tensorflow-lab`

CMD:
`docker run -it -p 8888:8888 -v %CD%:/CarND-TensorFlow-Lab udacity/carnd-tensorflow-lab`

PowerShell and CMD are two different shells, just like Bash and zsh are different shells on UNIX-like operating systems.

**Comment by sahiljuneja** [comment]
@MattHarrington I just run the commands from the docker quickstart terminal. That's clearly not powershell since the command you mention doesn't work in it. Also, does it have to be "CarND-TensorFlow-Lab" in that command. That should refer to the directory corresponding to the container which is "notebooks" as per the course page. 

@mslavescu Thanks, but the question is specific to Windows, so I don't think that command is useful. I honestly don't even wish to try it out because I can't recognize and understand most of that command, and I'd rather not mess around if I don't know what it does.

I will look into scp (although I am not sure if I can ssh into the docker since I am working via docker toolbox), but I thought there would be a more direct way to do this on Windows. the `-v`, I assumed, would help with that based on the forum discussion. Clearly that's not the case.

**Comment by MattHarrington** [comment]
@sahiljuneja Upon closer inspection, I see that the Docker image already contains the Jupyter Notebook.  That's why you can load a notebook no matter what mountpoint you use.  Try mounting it under `/foo` and you'll see things still work since it's just ignored.  Or, don't share a drive at all by omitting `-v ...`.

When you mount your local directory under the `/notebooks` mountpoint, the container's `/notebooks` is masked and the notebook is served from your host directory.  This presumably makes it easier to access the notebook from outside the Docker image.  Learn more here: [Mount a host directory as a data volume](https://docs.docker.com/engine/tutorials/dockervolumes/#/mount-a-host-directory-as-a-data-volume) for details.

The Windows examples containing Bash syntax won't work in PowerShell or the Command Prompt.  You have to use proper PowerShell or Command Prompt syntax.  Or, try Git Bash.

**Comment by sahiljuneja** [comment]
I needed to focus on remaining lectures since I am bit behind, so I didn't experiment much with Docker. For reference, if anyone does edit the course page to add additional details, the following is what I did -

- I cloned the folder in my D:// drive
- I ran the following command in my Docker Starter Terminal. I ran the command in the cloned folder in my D:// drive.

`docker run -p 8888:8888 -d --name udacity -v 'pwd':/notebooks udacity/carnd-tensorflow-lab`

- I worked on the notebook and solved the given problems. But I couldn't figure out how to save the data locally (on my system) while I was working. So I resorted to the following commands (in the same directory as above). It's important to note that the last parameter is supposed to be the directory where I want to copy the file from the container **and** we need to mention the name of this file as well. This can be repeated for any file (I also copied the pickle file).
`docker cp udacity:/notebooks/lab.ipynb lab.ipynb`

- Stop the docker container
`docker stop udacity`

- Remove the docker image 
`docker rm udacity`

That's what I am sticking with right now. If anyone can provide more detailed instructions that are convenient for Windows users that would be really great. Thanks to everyone for their help!

**Comment by domluna** [comment]
@sahiljuneja The instructions for the term 1 starter kit have been updated, goes into more details on the Windows end. https://github.com/udacity/CarND-Term1-Starter-Kit. You should be able to use that image for all the projects and labs. You could give that a shot, if it doesn't work let me know.

Another thing is TensorFlow now works natively on Windows so Docker might not even be required anymore.
