### ISSUE TITLE
Error message comes from drive.py

### ISSUE THREAD

**Issue by bartmate** [udacity/sdc-issue-reports#189]
This causes error for me:
model = model_from_json(json.load(jfile))
Error message: TypeError: the JSON object must be str, not 'dict'.

I use this one instead:
model = model_from_json( jfile.read() )
It seems to work.

**Comment by domluna** [comment]
@bartmate It's odd because this worked before. It looks like the Keras function has changed slightly or maybe a json change not sure. `json.load` returns a dictionary, even when wrapped in `str` it's not valid json since it's using single quotes instead of double quotes. Anyway, included your fix in the new file `drive.py` so it should be fine now.
