### ISSUE TITLE
Discrepancy between lectures on output height and width equations

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#227]
In 31. TF Convolution Layer of CNN lesson, the equation is -

```
new_height = (input_height - filter_height + 2 * P)/S + 1
 new_width = (input_width - filter_width + 2 * P)/S + 1
```

In the lecture following that, 32. we have

```
out_height = ceil(float(in_height - filter_height + 1) / float(strides[1]))
out_width  = ceil(float(in_width - filter_width + 1) / float(strides[2]))
```

The two don't match up. The former doesn't match up with https://www.tensorflow.org/versions/r0.11/api_docs/python/nn.html#convolution

In lecture 22.  For max-pooling

```
new_height = (input_height - filter_height)/S + 1
new_width = (input_width - filter_width)/S + 1
```

But for lecture 34. for pooling layer
```
out_height = ceil(float(in_height - filter_height + 1) / float(strides[1]))
out_width  = ceil(float(in_width - filter_width + 1) / float(strides[2]))
```

Lecture 36 also has different equations for both the conv layer and the pooling layer.

**Comment by domluna** [comment]
The way TensorFlow calculates the new height and width are slightly different. There's a note of that in the lecture https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/601ae704-1035-4287-8b11-e2c2716217ad/concepts/d0db3cab-ad70-46ec-9614-4dfc27dfc865. It was probably added after you already went through it. I don't think the fact they're different is an issue since there's more than one way to do it, i.e. changes again if you switch from `'VALID'` to `'SAME'` and vice-versa.
