### ISSUE TITLE
Advanced line finding - direction of gradient

### ISSUE THREAD

**Issue by bdholt1** [udacity/sdc-issue-reports#270]
In the lab for direction of the gradient, the solution code looks like this:

```
def dir_threshold(img, sobel_kernel=3, thresh=(0, np.pi/2)):
    # Grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    # Calculate the x and y gradients
    sobelx = cv2.Sobel(gray, cv2.CV_64F, 1, 0, ksize=sobel_kernel)
    sobely = cv2.Sobel(gray, cv2.CV_64F, 0, 1, ksize=sobel_kernel)
    # Take the absolute value of the gradient direction, 
    # apply a threshold, and create a binary image result
    # Here I'm suppressing annoying error messages
    with np.errstate(divide='ignore', invalid='ignore'):
        absgraddir = np.absolute(np.arctan(sobely/sobelx))
        binary_output =  np.zeros_like(absgraddir)
        binary_output[(absgraddir >= thresh[0]) & (absgraddir <= thresh[1])] = 1

    # Return the binary image
    return binary_output
```

The first point I want to make is that expecting students to know to suppress 'annoying warning messages' without consulting the solution is unreasonable.

The problem is that np.arctan() isn't usually the right approach to finding the arc tangent.  Instead most tutorials will suggest to use np.arctan2() which takes y and x separately and computes the element-wise arctan. See [Wikipedia](https://en.wikipedia.org/wiki/Atan2) for more information.

```
def dir_threshold(img, sobel_kernel=3, thresh=(0, np.pi/2)):
    
    # Apply the following steps to img
    # 1) Convert to grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    # 2) Take the gradient in x and y separately
    sobelx = cv2.Sobel(gray, cv2.CV_64F, 1, 0, sobel_kernel)
    sobely = cv2.Sobel(gray, cv2.CV_64F, 0, 1, sobel_kernel)
    # 3) Calculate the direction of the gradient
    dir_sobel = np.arctan2(sobely,sobelx)
    # 4) Take the absolute value
    abs_sobel = np.absolute(dir_sobel)
    # 5) Create a binary mask where direction thresholds are met
    binary_output = np.zeros_like(abs_sobel)
    binary_output[(abs_sobel >= thresh[0]) & (abs_sobel <= thresh[1])] = 1     
    # 6) Return this mask as your binary_output image
    return binary_output
```

When I use arctan2, it doesn't pass grading.  I respectfully submit that using arctan2 is a better solution and that the lab should be updated to use it instead, as well as making a note in the lecture notes before.

**Comment by ryan-keenan** [comment]
Thanks for your feedback!  

So, I had a look at this and while `np.arctan2()` gives the proper angle of the gradient from -pi to pi, in this exercise we're only concerned about angles from 0 to pi/2.  As it happens, either `np.arctan()` or `np.arctan2()` will give the result we're looking for in this exercise if used in the following way:

Option 1: `graddir = np.arctan2(np.absolute(sobely), np.absolute(sobelx))`
Option 2: `graddir = np.absolute(np.arctan(sobely/sobelx))`

However, your point is well taken that "annoying error messages" should not be part of the exercise and in this respect, `np.arctan2()` is superior because it catches nan's and divide by zeros.  

I have changed the quiz to suggest using `np.arctan2()` in the manner shown above and I now use it in the solution, allowing the removal of the cumbersome error suppression statement.  

Thanks again for helping to improve the content!

**Comment by bdholt1** [comment]
You're right that we don't care what quadrant the result is, so np.arctan() could have worked - the major problem was the errors that made it hard to figure out what was going wrong.

I tried again and see that the solution is now updated, but the submission criteria has not been updated too - "Oops, your result is different to what I expected" is still shown.

**Comment by ryan-keenan** [comment]
Hey, I just tried again and cutting and pasting the solution into the quiz gives the correct answer... were you trying a different solution?  I realize the output was kinda funny with the thresholds set at (0, np.pi/2) so I reset  these in the quiz to (0.7, 1.3).  Try refreshing the browser window and see if that helps.

**Comment by bdholt1** [comment]
It was my mistake - I was doing

```
    dir_sobel = np.arctan2(sobely,sobelx)
    abs_sobel = np.absolute(dir_sobel)
```

whereas the solution takes the absolutes of the sobels and computes the arctan

```
    absgraddir = np.arctan2(np.absolute(sobely), np.absolute(sobelx))
```
