### ISSUE TITLE
Update AWS GPU Instances Lecture

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#282]
1. There is no mention of which region to select for the AMI. That's important - lots of students asking about they not being able to find the AMI because they have selected (usually by default) some other region.

2. The AMI number is more important than the name. The image shows the number but having text makes it straightforward to search for the AMI. There are lots of other AMIs which have names similar to "udacity-carnd" and it can be confusing (especially if they have some other region selected).

**Comment by ChrisShepherd81** [comment]
The link below "13. Launch a Jupyter Notebook" is not working.
https://github.com/udacity/CarND-LeNet-Lab/blob/master/LeNet%20Lab%20Solution.ipynb

**Comment by dsilver829** [comment]
It should be possible to launch the AMI (or an identical copy of the AMI) in any AWS region - we're trying to keep the AMIs in sync across all regions. A few regions don't support GPUs, and we've added a note to the instructions about that.

**Comment by dsilver829** [comment]
In a perfect world, we'd just give out the AMI number. However, since the AMI number is different across regions, but we're able to make the AMI name stay the same, we've opted to go with that. The next time we update the AMIs, we will try to add a note specifying that our AMI is the "Official AMI of  the Udacity Self-Driving Car Engineer Nanodegree Program".
