### ISSUE TITLE
Display project due dates as actual dates in UTC time format or similiar

### ISSUE THREAD

**Issue by nachtfuchs** [udacity/sdc-issue-reports#291]
I think it is a good solution to display the due dates as you do so far in order to have a quick overview. 
Nevertheless, I would prefer an additional information about the due date in terms of a UTC time. The question I ask myself is: If the project is due in "one day" does it mean, that I can still work on it when it is due in "zero days"? 
By giving a specified UTC time and date, the date is unequivocal. This can be solved by displaying the exact date when the mouse cursor is hovered above the "coarse date".

**Comment by jessluls** [comment]
Hi there - because of the way our classroom works, we cannot set specific dates as due dates, but rather a number of days from the start of the class. This way, no matter which cohort you are in, the dates show up correctly. The classroom does not currently support different due dates for each cohort. 

Additionally - project due dates are meant to be guidelines that help you organize and understand what you need to accomplish in order to be on track to complete the nanodegree on time. You can still submit a project past its due date.
