### ISSUE TITLE
Wrong date of enrollment & therefore wrong project dealines?

### ISSUE THREAD

**Issue by ignisquisvir** [udacity/sdc-issue-reports#303]
It shows I am enrolled in the November cohort, but really I started in October. I also think my project deadlines are shifted, which is confusing.

**Comment by jessluls** [comment]
Hi there - sorry for the confusion! we altered start dates a bit in order to make project deadlines work the way we wanted them to (due dates are set as x number of days from the start of the class). The project deadlines did shift, but it was based on feedback from students that our first deadlines did not give enough time to complete the projects. We hope you'll agree that the extended timelines make for a better experience. You are, of course, welcome to submit a project earlier if you wish :).
