### ISSUE TITLE
Fixing scipy._lib.decorator for lab of "Intro. to Tensorflow"

### ISSUE THREAD

**Issue by jinchenglee** [udacity/sdc-issue-reports#308]
In section 35 Lab: TensorFlow Neural Network Lab, I met below error on Ubuntu 16.04 LTS native installation of python3.5:

_/usr/lib/python3/dist-packages/scipy/sparse/linalg/isolve/iterative.py in <module>()
      8 
      9 from scipy.sparse.linalg.interface import LinearOperator
---> 10 from scipy._lib.decorator import decorator
     11 from .utils import make_system
     12 from scipy._lib._util import _aligned_zeros

ImportError: No module named 'scipy._lib.decorator'_

I checked on internet, this is due to incomplete installation of python-decorator and/or python3-decorator. Details [here](https://bugs.launchpad.net/ubuntu/+source/python-scipy/+bug/1621803). I've verified that this fixed the issue. 

_This command fixed it for me. It reinstall the python 2 and 3 decorator package.

apt install --reinstall python\*-decorator

# Explanation:

On Debian place or python3 packages (/usr/lib/python3/dist-packages/) the scipy/_lib/decorator module is a symlink to the decorator module it self.

/usr/lib/python3/dist-packages/scipy/_lib# ls -l decorator.py
lrwxrwxrwx 1 root root 18 Sep 25 06:25 decorator.py -> ../../decorator.py

The package python-decorator and python3-decorator is a requirement for python-scipy and python3-scipy. According to apt, these decorator packages are installed. I checked the installed files with:

# dpkg -L python3-decorator
/.
/usr
/usr/lib
/usr/lib/python3
/usr/lib/python3/dist-packages
/usr/lib/python3/dist-packages/decorator.py
/usr/lib/python3/dist-packages/decorator-4.0.6.egg-info
(...)

But the file /usr/lib/python3/dist-packages/decorator.py was missing. Something in my system should (the user perhaps) should have messed with it. After I forced the reinstall of this packages, it came back to work again. But it's really strange this file gone missing._

**Comment by Brok-Bucholtz** [comment]
@jinchenglee,

Were you able to figure out why the file went missing?

**Comment by peterclearmetal** [comment]
[Ubuntu python-scipy bug 1533634](https://bugs.launchpad.net/ubuntu/+source/python-scipy/+bug/1533634) covers this.

The root cause is likely pip installing a newer version of decorator, which uninstalls the python-decorator provided by apt.  For me it was a [transitive dependency on decorator >= 4.1.0 in networkx](https://github.com/networkx/networkx/blob/0595dc7c7d33a94f9e46dbcb9cfce9ecd1a2329f/setup.py#L111).

I bet if you run this you'll see your decorator.py has been upgrade and is not longer under /usr/lib/python/ but is instead under /usr/local/lib/python 
```
pip freeze |grep decorator
python -c "import decorator; print(decorator.__file__)"
```
