### ISSUE TITLE
Lab: TensorFlow Neural Network - running on Windows

### ISSUE THREAD

**Issue by mdesksmartin** [udacity/sdc-issue-reports#319]
I struggled with the instructions for how to run on windows using docker toolbox.  ultimately, the solution was to not use the hyperlink in the text "Open a browser window and go *here*" and use the IP address 192.168.99.100 which i guess is the IP of the docker container(?).  i am new to docker so it is a little mystical that i run git clone from a mingw shell that puts files on the windows filesystem and then launch a docker container hosted in virtualbox that somehow connects back to the filesystem and exposes a URL with an IP that i can't figure out how to identify.

also, in the sections about running commands from the shell on windows, it's not crystal clear to a docker novice if you are supposed to be running the git clone and docker run commands in the windows command prompt or the docker shell.  IMHO, the instructions would be easier to follow if broken into one section for windows and one for mac/linux with each one giving the steps from start to finish on the platform.

**Comment by Brok-Bucholtz** [comment]
@mdesksmartin,

I split up the instructions to Windows and Linux/OS X.  I also made some instructions more clear about where to run the command.  We're are currently working on creating documentation for docker, so that issue will be addressed in the future.  Keep letting us know of any issues you see!
