### ISSUE TITLE
drive.py breaks on the latest keras version

### ISSUE THREAD

**Issue by subodh-malgonde** [udacity/sdc-issue-reports#333]
On the latest keras version (1.2.0), the drive.py code for behavioral cloning project doesn't work. The error is on line #68 which is `model = model_from_json(jfile.read())`

The error thrown is `class_name = config["class_name"], TypeError: string indices must be integers`

When I change the line to `model = model_from_json(json.loads(jfile.read()))`, the code works

**Comment by domluna** [comment]
I'm not sure why this occurs but I added a conditional to the latest `drive.py`:

```
if keras.__version__ >= "1.2.0":
    model = model_from_json(json.loads(jfile.read()))
else:
    model = model_from_json(jfile.read())
```

Temporary solution :smile:

**Comment by domluna** [comment]
@subodh-malgonde  It's how you saved the file `json.dump(model.to_json(), outfile)` that's causing this issue. `model.to_json()` already serializes  it to JSON so calling `json.dump` simply adds another layer of serialization. This makes the output a string instead of a dictionary, i.e.

```"{\"config\": ... \"keras_version\": \"1.2.0\"}"```

instead of 

```{"config": ... "keras_version": "1.2.0"}```

```class_name = config["class_name"], TypeError: string indices must be integers```. This is being thrown because you're trying to index a string (`config`) with a string `"class_name"`.

Saving the file with:

```
with open('./model.json', 'w') as outfile:
    outfile.write(model.to_json())
```

circumvents this problem. I added a note to the newest `drive.py` indicating to use your solution if it was saved in a similar fashion to the way you saved it though.

**Comment by subodh-malgonde** [comment]
Thanks for pointing out @domluna .
