### ISSUE TITLE
Lesson 2 Finding Lane Lines 3. Color selection code example

### ISSUE THREAD

**Issue by Kenadia** [udacity/sdc-issue-reports#385]
In this section you talk about selecting pixels to be set to black. Then there is the line:

“In the code snippet above, red_threshold, green_threshold and blue_threshold are all set to 0, which implies all pixels will be included in the selection.”

This is incorrect / badly worded. Setting the thresholds to 0 implies no pixels will be selected and all pixels will be retained.

**Comment by ryan-keenan** [comment]
Hi thanks for pointing this out!  I've changed things to read "After that, all pixels that meet my color criterion (those above the threshold) will be retained, and those that do not (below the threshold) will be blacked out."  

If the threshold is set to 0 that means no pixels are below the threshold and all pixels will be retained so that next sentence is correct, though perhaps confusing in the previous context.
