### ISSUE TITLE
Lab: Keras jupyter notebook does not work

### ISSUE THREAD

**Issue by wfs** [udacity/sdc-issue-reports#410]
traffic-sign-classification-with-keras-solution.ipynb only gets ~=20% through training progress bar, before time out.

**Comment by wfs** [comment]
using :
- ubuntu 16.04
- chrome
- carnd-term1
- tensorflow                0.12.1
- tensorflow-gpu            0.12.1

**Comment by wfs** [comment]
Glitch may be caused by CarND-Keras-Lab being written / tested on a machine with ~/anaconda3/envs setup and not the default ~/miniconda3?

**Comment by sstormm** [comment]
i had this same problem on windows 10 and chrome and reported it.  if you add the argument "verbose=2" to the method call, it doesn't crash.  i think the issue is the rapid send/receive loop between chrome and the jupyter notebook process that causes one of those things to give up the ghost.  i was also using the gpu version of the library so maybe the GPU-intensive work plus the rapid requests for browser refresh cause an issue?

**Comment by Brok-Bucholtz** [comment]
I think this is related to #361.

**Comment by domluna** [comment]
https://github.com/fchollet/keras/pull/5165 seems to be relevant to this. Alternatively, as already reported playing around with the verbose argument might help.

**Comment by domluna** [comment]
Added verbose statements to all the fit functions should work fine now. Ideally Jupyter should be able to handle the animation on its own.
