### ISSUE TITLE
Confusing y axis starts at the top

### ISSUE THREAD

**Issue by rm51** [udacity/sdc-issue-reports#42]
It would be good if the x axis numbers could be moved to the top of the photo rather than the bottom since it starts from the top left. Also it would be good if that axis could be shown on earlier quizes such as the Color Region one rather than just on the Hough Transform one which is later in the course.

**Comment by rm51** [comment]
The y axis in the quizes for Lesson 1 start at the top rather than the bottom. This is confusing if people also run the code on their local machine as the values will be different. Is there a specific reason it is that way? If so, perhaps it could be included in the lesson since it seems to be different than starting y=0 at the bottomg.

**Comment by rm51** [comment]
<img width="634" alt="screen shot 2016-10-28 at 12 26 23 pm" src="https://cloud.githubusercontent.com/assets/7563076/19814181/1d0d7890-9d0b-11e6-8cd1-e03bdeba8058.png">

**Comment by ryan-keenan** [comment]
Thanks for pointing this out.  In fact, the standard for image processing / computer vision is to have the origin in the upper left (makes sense if you're thinking in terms of images as matrices).  I've changed the x and y axis representations in the video describing "images as functions" in the section called "Canny Edge Detection" along with a note below the video.  Might try to work this into the lesson more prominently.   The quizzes should work the same on a local machine because in reading / displaying images the default is having the origin in the upper left.
