### ISSUE TITLE
Decision Trees > Information Gain Calcs 7+

### ISSUE THREAD

**Issue by mdesksmartin** [udacity/sdc-issue-reports#460]
the choice of slow (s), fast (f), steep (s), flat (f), make some of the lesson a bit confusing because the abbreviations are exactly the same.  when the lesson gets to part 7, i answered the question correctly about entropy for 'bumpiness' but for the wrong reason.  it would have helped me for the video to explain why the entropy is 1.0 (because 'bumpy' maps to 1 'fast' and 1 'slow', not because the bumpy split has 2 bumpy and 2 flat).

overall, too, the very short duration of the videos and the loading time made it hard for me personally to maintain continuity.  i would prefer a single (maybe slightly longer) continuous video with all of the content and then the short snippets of quiz as just static pages with graphics.  i found my self both impatient for the pages to load but also feeling like i needed more time after some of the answers to let the ideas sink in (like i wanted to just sit and stare at a page for a minute or two).

**Comment by cameronwp** [comment]
We'll look into the Decision Tree issue.

As to the Udacity style, thanks for your feedback! We're always tweaking our teaching style. While we won't be able to change this particular lesson, we'll take your feedback into account with future lessons.

**Comment by andrewpaster** [comment]
Hey, yeah I agree that the labeling could have been done more clearly. My best suggestion is to take parts 1-6 and then draw out the trees and equations for videos 7-10 following the same patterns she used earlier. Since these lectures come from a different course, I can't add things or change things very easily unfortunately. But we'll keep this in mind if we end up revamping the decision trees lectures.
