### ISSUE TITLE
T2.L05 General - Kalman filter terminology and sequence

### ISSUE THREAD

**Issue by sstormm** [udacity/sdc-issue-reports#524]
I am finding the terminology used for the Kalman filter steps to be confusing.  The terms "update step", "measurement step", "prediction step", "state transition" and probably more are used. I get that there are 2 steps -- measurement and prediction -- but all these other terms make it confusing to follow as a new learner.  Also, I can't seem to wrap my head around whether or not there is a clear sequence to measure-predict.  in some of the content it seems to be that predict comes first  and then measure ("kalman filter equations in c++ Part 1", "Additional Info about the last quiz" shows prediction-> update) but then in some code quizzes ("Kalman Filter Equations in C++ Part 2"), the measurement logic is before the prediction logic in the code.  I think the content could be clearer about whether there is a required order and what that order is.

**Comment by andrewpaster** [comment]
Yeah the EKF lesson is a tough one. In the very first slide "2. Lesson Map and Fusion Flow", it shows the order that things would happen in. 

The first thing you need is a measurement because otherwise there is no location information or even information that the object exists unless a sensor picked it up. But you just initialize location values with the measurement. 

Then you essentially wait for a new measurement to come in. Once it does, you calculate where you think the object will be since the last time you received a measurement. That's the prediction step. Then you compare where you think the object is with what the sensor says and update the location with the new sensor information. 

I'll add some extra text about this at the beginning of the EKF lesson.
