### ISSUE TITLE
Kalman Filter Quiz 1

### ISSUE THREAD

**Issue by dsilver829** [udacity/sdc-issue-reports#555]
A student asked if "Kalman filter quiz 1" is erroneous, because it implies doing measurement before prediction.

https://drive.google.com/file/d/0B0Hd8k-wUrTsdU1pbllWUG5OSFk/view?usp=sharing

We need to take a look and see if this is an error or if it's just not clear.

**Comment by dsilver829** [comment]
A student asked if "Kalman filter quiz 1" is erroneous, because it implies doing measurement before prediction.

https://drive.google.com/file/d/0B0Hd8k-wUrTsdU1pbllWUG5OSFk/view?usp=sharing

We need to take a look and see if this is an error or if it's just not clear.

**Comment by cameronwp** [comment]
I'm not sure I'm looking in the right place. Could you find out exactly which quiz they're seeing this?

**Comment by ChrisShepherd81** [comment]
It's the "Kalman Filter Equations in C++ Part1/Part2"

It starts with the measurement update, calculate states and afterwards do the predition. So for the given measurements {1, 2, 3} the result output of the given solution for the x positions is {0.999001,  2.998, 3.99967}. That looks wrong to me too. 

My  solution with a prediction step before the measurement was not accepted on submit.
```
// KF Prediction step
VectorXd x_prime = (F * x) + u;
MatrixXd P_prime = (F*P*F.transpose()) + Q;

// KF Measurement update step
VectorXd y = z - (H*x_prime);
MatrixXd S = (H*P_prime*H.transpose()) + R;
MatrixXd K = P_prime*H.transpose()*S.inverse();

// new state
x = x_prime + (K*y);
P = (I - K*H)*P_prime;
```

**Comment by baumanab** [comment]
Thank you for bringing this up.  I can see where there could be some confusion since the flow chart shows predict and then update.  However, update --> predict is in line with Sebastian's lessons, which the quiz references.  To some extent this is cyclical, we predict, then we update, over and over.  Measurement update gives us the tightest possible distribution with the best evidence we have.  The predict step widens our distribution, we then meausre to tighten, and then predict, etc.  In any case we are reviewing this quiz to resolve.

**Comment by baumanab** [comment]
After conferring with some colleagues we did determine that this is the case.  Please let us know if we can clarify in any way.

**Comment by megaserg** [comment]
All lecture material before describes the loop as: make prediction **first**, and then use measurement **to correct our belief** (exact quote). At no point before it was suggested that measurement step could come first. Sure, there is no difference in the long run due to the cyclical nature of the process, but I feel that for a newcomer this inconsistency should be explained.

One option is to make a comment before the quiz why the measurement should come first -something along the lines of #524 answer.

**Comment by mvirgo** [comment]
@megaserg Added some clarifying text here, thank you!
