### ISSUE TITLE
OR Image is Wrong

### ISSUE THREAD

**Issue by dsilver829** [udacity/sdc-issue-reports#559]
the "OR & NOT Perceptron Quiz", the pic of OR IN and output is wrong probably?  x1 In 1 OR x2 in 1 yield to 0 output?? is this wrong?

IN 1 + IN 1 = OUT 0, I think this is wrong. in ""OR & NOT Perceptron Quiz""

**Comment by brahmwindeler** [comment]
I'm going back, completing the new versions of the lessons and noticed this, too. The truth table shown is for XOR.

**Comment by andrewpaster** [comment]
I'm looking at this now, and it seems somebody fixed this already. The OR truth table in the classroom has
1 1 -> 1
1 0 -> 1
0 1 -> 1
0 0 -> 0

**Comment by jwetherb** [comment]
I'm in the September 2017 cohort, taking term 1, and this bug is still there. The test below:

    output = int(linear_combination >= 0)

doesn't match the "if 0 then 1 elif 1 then 0" result I was expecting. Not sure whether the definition of the NOT perceptron in the lesson is wrong, or the output derivation step above (which returns 0 for < 0 and 1 for anything else).
