### ISSUE TITLE
T2 - Particle Filters/2 - Refers to histogram filters which was not presented earlier

### ISSUE THREAD

**Issue by bartmate** [udacity/sdc-issue-reports#607]
T2 - Particle Filters/2-5. Quizes - Refers to histogram filters which was not presented earlier

**Comment by jessluls** [comment]
Hi there! We have not released the entire Localization content just yet. Sounds like you got ahead - that's great! Some of the content is visible because it comes from Sebastian's AI for Robotics course, which is what you are seeing right now. We'll be releasing the remaining content on Monday and hopefully things will be clearer then. Thanks!
