### ISSUE TITLE
Project Submission Time ignores local Time Zone

### ISSUE THREAD

**Issue by Daniel-Prado** [udacity/sdc-issue-reports#630]
P2 due date for my cohort is March 27, 2017 at 11:59 PM PST. 
Right now it's March 27 9:24PM PST.
However, as I am based in NYC, and here it's already March 28th 12:24 AM EST,  the Udacity webpage says that I am "past due" which is not correct.

**Comment by jessluls** [comment]
I think this is because the classroom is set to GMT. The deadlines you see in your classroom are suggestions for when you should ideally pass each project. They are meant to help keep you on track so that you maintain an appropriate pace throughout the program–one that will see you graduate on time!
