### ISSUE TITLE
Not a good idea to use mutable types as default argument in python functions

### ISSUE THREAD

**Issue by dhruvbaldawa** [udacity/sdc-issue-reports#64]
This is not really a bug, but we should refrain from using mutable types as default arguments to python functions / methods.

http://docs.quantifiedcode.com/python-anti-patterns/correctness/mutable_default_value_as_argument.html

http://docs.python-guide.org/en/latest/writing/gotchas/

![image](https://cloud.githubusercontent.com/assets/380197/19858728/a1697c20-9fa8-11e6-8ba1-3cf155fecae2.png)

**Comment by Brok-Bucholtz** [comment]
@dhruvbaldawa 

I completely agree!  We'll remove the code smell the next time we make changes to the Layer Initialization function.  Since each call to the function passes in a array, it's not a problem.  It would be an easy fix if it was in a repo, but we have to change each quiz that uses MiniFlow.
