### ISSUE TITLE
Clarify Scalar vs. Vector Velocity

### ISSUE THREAD

**Issue by dsilver829** [udacity/sdc-issue-reports#657]
Gurgen Hayrapetyan [3:24 PM] 
Just a thought, it could be helpful to add a note to the unscented Kalman Filter lectures that velocity as used in the lectures refers to the scalar velocity or speed as opposed to vector velocity (i.e. by the physics definition the car driving in the circle could have constant speed, but does not have constant velocity as is stated in the module).  This is a minor point, as in many languages the word for the vector velocity and its magnitude is the same, and is clear from the context, but might be confusing for some? I apologize if this has been addressed in lectures and I missed it.

**Comment by andrewpaster** [comment]
In lesson 3,  Dominik says, "they can also move with a constant turn rate and a  constant velocity magnitude...instead of describing the velocity with vx and vy, we use the speed and yaw angle...the speed is the magnitude of the velocity..constant yaw rate and constant speed...". 

Lesson 4 says "unfortunately, the velocity in the x direction is not part of the state vector...but the speed v and yaw rate of psi are both elements of the state vector"

Seems like Dominik was clear that this was speed (magnitude of velocity) and not velocity like in EKF
