### ISSUE TITLE
Project: EKF no clear indication of u = 0

### ISSUE THREAD

**Issue by pcarney8** [udacity/sdc-issue-reports#678]
In term 2, Project Extended Kalman Filters, I could not find anywhere that said we were setting u = 0 for the prediction equation `x' = F*x + u` After reading through the forums, and posing the question, it appears we're dealing with measurement noise in the R matrix and ignoring u. Could we explicitly state that it's being set to 0 or ignored? Thanks

**Comment by andrewpaster** [comment]
Hi thanks for pointing this out. I've added some clarifications throughout the EKF lectures about this. 

u represents noise. It's set to zero because noise is assumed to have a mean value of zero. 
The x' equation is updating the mean state, so the mean noise gets used in that equation. It's not being ignored necessarily, it's just assumed to equal zero. 

But u is also assumed to have a gaussian distribution, which means it has a variance. The variance shows up in the Q matrix. So even though mean noise is zero (u = 0), noise isn't ignored because its variance still shows up in the update step.

The noise in the lecture is modeled as acceleration. If u = 1 for example, it's like saying acceleration on average is 1 m/s^2 + or - some uncertainty.
