### ISSUE TITLE
Inaccuracy in Sobel operator definition

### ISSUE THREAD

**Issue by fantauzzi** [udacity/sdc-issue-reports#699]
Shouldn't the Sobel operator be 1/8th of what indicated in the lecture? Both for S-with-x and S-with-y.

In Advanced Lane Finding, Sobel Operator: https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/2b62a1c3-e151-4a0e-b6b6-e424fa46ceab/lessons/40ec78ee-fb7c-4b53-94a8-028c5c60b858/concepts/e6115672-155d-4c10-b640-fe20a4f4b0a6

**Comment by baumanab** [comment]
Would you mind elaborating on how you arrived at 1/8th?

**Comment by fantauzzi** [comment]
I believe it is a normalization value. This is where I first learned about it  https://classroom.udacity.com/courses/ud810/lessons/2673608575/concepts/35179090230923

**Comment by baumanab** [comment]
Thank you, that makes sense.  It looks like a 1/8 normalization is common for gradients since it normalizes to one grey scale per pixel.  I did some research into this and found that normalization is not typically used for edge detection and is sometimes used for gradient detection.  However, the value depends on the application (what you need to scale to).  We are going to hold off on making changes for now.
