### ISSUE TITLE
T1.AdvancedLaneFinding.6 meaning of r

### ISSUE THREAD

**Issue by troyjlee** [udacity/sdc-issue-reports#742]
In the text there is the formula
x_corrected = x(1 + k_1 r^2 + k_2 r^4 + k_3 r^6)

My understanding of the text above this formula is that we are given a (distorted) x,y and the goal is to compute x_corrected, y_corrected.  However, we cannot use this equation to do it since r is defined in terms of x_corrected.  

If instead we are given x_corrected, y_corrected, so that r is known, and the goal is compute where x,y will appear in the distorted camera image, then this equation would make sense. However, it would be more natural to write it as 
x = x_corrected(1 + k_1 r^2 + k_2 r^4 + k_3 r^6)

That is the way it is done in this wikipedia article in the section Software correction.
https://en.wikipedia.org/wiki/Distortion_(optics)

**Comment by troyjlee** [comment]
I believe the correct formula used in opencv is
x_distorted = x_ideal(1 + k_1 r^2 + k_2 r^4 + k_3 r^6),
where r is as you have defined it.

We start with a 3D world point (X,Y,Z) which is mapped to (x_ideal, y_ideal) by an ideal pinhole camera.  The distortion of our actual camera shifts (x_ideal, y_ideal) to (x_distorted, y_distorted) by the above formula.  The process is explained on this opencv doc page, 
http://docs.opencv.org/2.4.1/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html

I realize that the formula you give unfortunately also appears in opencv docs.
http://docs.opencv.org/2.4/doc/tutorials/calib3d/camera_calibration/camera_calibration.html

Given this conflicting documentation, I coded up my own projectPoints function using the top formula.  This agreed with the opencv projectPoints function to the 5th decimal place.  Thus I think the top formula is correct and the formula given in the Udacity notes is not how it is done in opencv.

**Comment by baumanab** [comment]
Thank you for reporting this.  This formula (`x_distorted = x_ideal(1 + k_1 r^2 + k_2 r^4 + k_3 r^6)`) does make sense in terms of applying r to an ideal image to create a distorted image.  We will confirm and make any required changes.

**Comment by mvirgo** [comment]
After looking into the underlying research paper for Brown's Method (referenced in the Wikipedia article, or for which the very original equation can be found [here](https://www.rose-hulman.edu/class/cs/OldFiles/csse461/handouts/Day21/Brown71.pdf)), it appears that the classroom equation is technically appropriate - to reach a corrected image, the distorted image is multiplied by the coefficients. 

However, as you mentioned, and as mentioned in the [direct link](http://researchspace.csir.co.za/dspace/bitstream/handle/10204/3168/De%20Villiers_2008.pdf;jsessionid=38EEDFB0F3CF79B82E36C6B0599B0994?sequence=1) in Wikipedia, typically this is done in the opposite fashion - "However, in practice, one generates an undistorted image in the opposite manner. One starts with a blank slate for the undistorted image, and for every pixel determine which distorted pixel to use." Essentially, the classroom equation is correct, but is not the typical actual use case. In the research paper, they actually show Brown's model can be used to mostly accurately do this in opposite fashion (see section 5 of the wikipedia direct link), using inverted coefficients. 

Since the classroom logic follows better if we consider applying the coefficients to the distorted image to reach the corrected image, I have updated the equation as requested.
