### ISSUE TITLE
error in P4: Calibrating Your Camera

### ISSUE THREAD

**Issue by asimay** [udacity/sdc-issue-reports#793]
the description: grayscale image shape array gray.shape[::-1]. This returns the image height and width in pixel values like (960, 1280).
should be:
grayscale image shape array gray.shape[::-1]. This returns the image width  and height in pixel values like (1280, 960).

**Comment by asimay** [comment]
print(tmp_img.shape)

print(tmp_gray.shape[::-1])
--> output
(720, 1280, 3)
(1280, 720)

**Comment by asimay** [comment]
I tested it.

**Comment by asimay** [comment]
the related code also should be changed:
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

change   gray.shape[::-1] -->  gray.shape

**Comment by leros** [comment]
It really should be gray.shape for cv2.calibrateCamera.  4 months have passed, but the problem is still there. Unbelievable. ..

**Comment by baumanab** [comment]
Thank you for the feedback.  I'm taking a closer look at this.  I'm just orienting myself to this specific content and making changes.  Please correct me if I am wrong, but gray.shape or gray.shape[::-1] should work (there was a typo in code where :-1 was used instead of ::-1).  Is the motivation for changing to gray.shape avoiding an unnecessary computational step (array reversal)?

**Comment by baumanab** [comment]
It's not clear from the [documentation and examples](http://docs.opencv.org/trunk/dc/dbb/tutorial_py_calibration.html) why the reversed array is used.  The errors above are corrected.  We are staying with the reversed array, for now, to maintain alignment with the documentation and examples.
