### ISSUE TITLE
Using auto for Eigen expressions in CarND-MPC-Project and CarND-MPC-Quizzes

### ISSUE THREAD

**Issue by dimaga** [udacity/sdc-issue-reports#823]
It is recommended not to use C++11 auto with Eigen expressions: see http://eigen.tuxfamily.org/dox/TopicPitfalls.html
However, it is widely used in https://github.com/udacity/CarND-MPC-Quizzes/blob/master/polyfit/src/main.cpp and https://github.com/udacity/CarND-MPC-Project/blob/master/src/main.cpp

**Comment by domluna** [comment]
@dimaga I believe the biggest use is in the `polyfit` function and, in that case, the result is exactly what we want. It's true you have to be careful when using `auto` with Eigen though.

For example:

```cpp
auto Q = A.householderQr();
auto result = Q.solve(yvals);
```

the above works as we would expect but:

```cpp
auto result = A.householderQr().solve(yvals);
```

does not.

Since the current setup works I see no reason to really change it but you bring up a good point nonetheless.
