### ISSUE TITLE
T3, L09.8 Transposed Convolution Quiz Error

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#951]
1. The solution to the quiz in the IDE throws an error, because of the padding parameter being `"same"`  instead of capitalized `"SAME"`

2. The number of channels of input is different than the number of channels of the output in the solution in the IDE. Shouldn't the number of channels stay the same when upscaling? The input has 3 whereas the output has 5 as per the Solution.

3. The solution to the Quiz in the next section doesn't match with the solution to the Quiz in the IDE. Not sure if that's intentional.

**Comment by baumanab** [comment]
Thanks for letting us know about this. 

1. I'm not sure about this item as the current version of the quiz does not use the padding parameter "SAME".  

2. The output shape should be greater than the input shape since this is upsampling (resampling at a higher rate or resolution).

3.  It looks like the IDE solution and concept solution are now aligned.
