### ISSUE TITLE
T3, Semantic Segmentation Project - vgg_data

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#961]
Currently we have vgg_tag = 'vgg16'

But the tf.saved_model.loader.load documentation doesn't clearly specify how to pass that. I just thought it was supposed to be a string only.

Do you think it's easier/better to have it defined as vgg_tag = ['vgg16'] directly for the students? 

The test case clearly shows what to do, but seems kind of redundant to figure this out through the test cases, and since the documentation is lacking, maybe it's easier to just set it in a list. Let me know what you think.

**Comment by baumanab** [comment]
related to #962

**Comment by sahiljuneja** [comment]
I'm sorry, but can you please clarify your workflow here?

I am not sure how this relates to 962, because they are two separate issues. Maybe I am not understanding your preferred workflow so a clarification could clear up the confusion for me :)

**Comment by baumanab** [comment]
Sorry for any confusion.  We understand that these are two separate issues.  If they were the same they would be marked as duplicates.  Instead, I've marked them as related so that when we address the comments we can track where there are related (subject matter relations, project relations, lesson relations, etc.) to increase efficiency (we can address projects or lessons etc. as a whole).  The tags also serve this purpose to some extent so that the team can filter issues by relationships and labels.  Does that make sense?

**Comment by sahiljuneja** [comment]
Aah, yes. Understood now. Thanks for clarifying!

**Comment by baumanab** [comment]
Sorry for the delay in response.  I do see your point and it is challenging to determine the best course.  My concern is that if we define the tag variable as a list object it could create issues when more than one tag is applied.  We aren't doing that here, but it could happen in other applications.  See the documentation [here](https://www.tensorflow.org/api_docs/python/tf/saved_model/loader/load )

> tags: Set of string tags to identify the required MetaGraphDef. These should correspond to the tags used when saving the variables using the SavedModel save() API. 

Does that make sense?
