### ISSUE TITLE
Kidnapped Vehicle Project: Incorrect Formula in the classroom

### ISSUE THREAD

**Issue by subodh-malgonde** [udacity/sdc-issue-reports#998]
The formula mentioned for transforming the landmarks from the vehicle's coordinate system to the map coordinate system is incorrect. I am referring to [this section of the classroom](https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/2c318113-724b-4f9f-860c-cb334e6e4ad7/lessons/5c50790c-5370-4c80-aff6-334659d5c0d9/concepts/97f45106-adf4-45f1-b919-9675b3c990e0). The formula mentioned right now is:

    xm = xp​​ + (cosθ×xo) + (sinθ×yo)
    ym = yp + (−sinθ×xo) + (cosθ×yo)

This is incorrect. The Q&A video has the correct formula, which is:

    xm = xp​​ + (cosθ×xo) - (sinθ×yo)
    ym = yp + (sinθ×xo) + (cosθ×yo)

Notice the difference in the signs.

**Comment by baumanab** [comment]
There does seem to be a lot of confusion regarding the formulas.  Would you mind clarifying the formula from the Q/A video?  I think the confusion lies in the clockwise vs. counterclockwise transformation matrix which differ only in where the - sign is.  In the classroom, the rotation is -90, so there are two ways to solve this.

1.  Use the counter-clockwise rotation with 90 degrees
2.  Use the clockwise rotation with -90 degrees

We went with the latter since that is the actual rotation.  We plan on adding a video to explain this.  Does this make sense?  We'd like to make this all as clear as possible, so please let us know your thoughts.

This is a brief presentation of both mastrices: https://www.miniphysics.com/coordinate-transformation-under-rotation.html

**Comment by baumanab** [comment]
I was wondering if it would help if we mention both ways to solve?  Either will work for the project, one involves reversing the sign of theta, the other does not?  What would help make things more clear?

**Comment by subodh-malgonde** [comment]
Hi,

The formula mentioned in the Q&A video is the second formula I mentioned in the OP. I am attaching a screenshot. The formula appears around the 30:40 mark.

![screen shot 2017-08-14 at 11 18 47 pm](https://user-images.githubusercontent.com/5463437/29284117-124dd03c-8147-11e7-916b-c6ea9da8fa94.png)

I think just adding a note about this i.e. mentioning that the formula depends on the convention being used for theta should suffice. This along with the fact that the convention being used in the simulator is 'anti-clockwise rotation' is positive.

**Comment by baumanab** [comment]
Thank you for confirming.  This was what I found as well.  We will add a note about this and let student's decide how they wish to approach the solution.  Thanks a lot for your feedback, it is very helpul.

**Comment by baumanab** [comment]
The formulas and solutions have now been updated to recognize both rotational matrices and explain which is which and theta vs. -theta.  An animation/video is in the works to show coordinate rotation.
